/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsAndTemplatesRouteImport } from './routes/tools-and-templates'
import { Route as ProductLabRouteImport } from './routes/product-lab'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'

const ToolsAndTemplatesRoute = ToolsAndTemplatesRouteImport.update({
  id: '/tools-and-templates',
  path: '/tools-and-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductLabRoute = ProductLabRouteImport.update({
  id: '/product-lab',
  path: '/product-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/courses': typeof CoursesRoute
  '/product-lab': typeof ProductLabRoute
  '/tools-and-templates': typeof ToolsAndTemplatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/courses': typeof CoursesRoute
  '/product-lab': typeof ProductLabRoute
  '/tools-and-templates': typeof ToolsAndTemplatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/courses': typeof CoursesRoute
  '/product-lab': typeof ProductLabRoute
  '/tools-and-templates': typeof ToolsAndTemplatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/courses'
    | '/product-lab'
    | '/tools-and-templates'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog' | '/courses' | '/product-lab' | '/tools-and-templates'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/courses'
    | '/product-lab'
    | '/tools-and-templates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  CoursesRoute: typeof CoursesRoute
  ProductLabRoute: typeof ProductLabRoute
  ToolsAndTemplatesRoute: typeof ToolsAndTemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools-and-templates': {
      id: '/tools-and-templates'
      path: '/tools-and-templates'
      fullPath: '/tools-and-templates'
      preLoaderRoute: typeof ToolsAndTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-lab': {
      id: '/product-lab'
      path: '/product-lab'
      fullPath: '/product-lab'
      preLoaderRoute: typeof ProductLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  CoursesRoute: CoursesRoute,
  ProductLabRoute: ProductLabRoute,
  ToolsAndTemplatesRoute: ToolsAndTemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
